kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: gluster-heketi
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
    resturl: "http://172.27.180.208:8080" 
    restuser: "admin" 
    secretName: "heketi-secret"
    secretNamespace: "default"
    volumetype: "replicate:2"
    volumenameprefix: "k8s-dev"
    # heketi-cli cluster list
    clusterid: "c8548b8bf349a85be2cce8f081e74bc1"
